### PR TITLE
Update to use `go install` for tools

### LINKED ISSUE #10: `make tools` fails due to dependency problem
# What
`make tools` fails at the command below due to dependency problem.
https://github.com/yamamoto-febc/terraform-provider-gmailfilter/blob/6588f9d00118560847d1bc868433e1ba3da4f7f8/GNUmakefile#L14

The error log is below.
```console
$ make tools
GO111MODULE=off go get github.com/x-motemen/gobump/cmd/gobump
GO111MODULE=off go get golang.org/x/tools/cmd/goimports
GO111MODULE=off go get github.com/tcnksm/ghr
GO111MODULE=off go get github.com/bflad/tfproviderdocs
# github.com/bflad/tfproviderdocs/check
../../.go/src/github.com/bflad/tfproviderdocs/check/directory.go:109:31: not enough arguments in call to doublestar.Glob
	have (string)
	want (fs.FS, string)
make: *** [tools] Error 2
```

# Why
[tfproviderdocs](https://github.com/bflad/tfproviderdocs) depends on [doublestar](https://github.com/bmatcuk/doublestar), and latest [doublestar](https://github.com/bmatcuk/doublestar) uses `io/fs` package.
`io/fs` was added on Go 1.16 however it is used in latest [doublestar](https://github.com/bmatcuk/doublestar) and version of Go in this repo is 1.13.
To my understanding, GOPATH mode can't specify version of module.

# Proposed Solution
Use Go Modules mode to manage [tfproviderdocs](https://github.com/bflad/tfproviderdocs).

### PR DESCRIPTION
**Pull request by rakiyoshi**
close #10 

This fixes #10:
- Upgrade Go version to 1.16 from 1.14
- Update to install tools below with `go install`.
  - https://github.com/yamamoto-febc/terraform-provider-gmailfilter/blob/60b3d4574a6b716a86026f166c958d89a50f055e/GNUmakefile#L10-L17
  - All versions specified in the commit are the latest at the moment.

**Updated: Install tools with not Go Modules mode but `go install`.**

### CODE REVIEW

**Review by yamamoto-febc — COMMENTED** [review]
Hey @rakiyoshi , thanks for the PR:pray:

How did you add the tfproviderdocs to go.mod?
I think tfproviderdocs will be removed from go.mod when exec  `go mod tidy`.

For now, here are some ideas I just came up with.
- Upgrade to go 1.16, and specify the version with `go install` and install the dependent tools in `make tools`.
- Create a tools.go (ref: https://github.com/golang/go/wiki/Modules#how-can-i-track-tool-dependencies-for-a-module)

I haven't checked if it works yet, but I think it's easier to upgrade to Go 1.16 than to use the tools.go.

**Comment updated: `tools dir` -> `tools.go`**

**Comment by rakiyoshi** [comment]
Hi @yamamoto-febc, thank you for your response.

> How did you add the tfproviderdocs to go.mod?

I edited `go.mod` manually (like `package.json`) and installed them, but I realized that was bad way.
I'll revert its commit.

> I haven't checked if it works yet, but I think it's easier to upgrade to Go 1.16 than to use the tools.go.

I agree with your idea. 
BTW, should I change to use `go install` for not only `tfprovderdocs` but also other packages?

**Comment by yamamoto-febc** [comment]
> should I change to use go install for not only tfprovderdocs but also other packages?

Yeah, I would appreciate it if you could fix it.

**Comment by rakiyoshi** [comment]
@yamamoto-febc I upgrade Go versions and updated to install tools with not Go Modules mode but `go install`.
Could you re-review this PR? :pray:

**Review by yamamoto-febc — APPROVED** [review]
Very cool, thank you!!

**Pull request merged**
